---
title: "steps"
author: "Pupso"
date: "7/27/2020"
output: html_document
---

```{r}
source("util.r")
```


```{r}
df_steps = combine_dfs("/home/ludwig/Bachelorarbeit/voting-protocols/data_cluster/data_steps/data","step")
```


```{r}
  df_steps %>% 
  mutate(steps = factor(steps)) %>% 
  filter(user_opinion_function == "Konsens") %>% 
  ggplot_cus() + 
  aes(x = area_under_gini, y = area_under_ndcg, color = steps) + 
  geom_point() + 
  facet_wrap(~relevance_gravity)
```

```{r}
df_steps %>% 
  mutate(init_score = factor(init_score)) %>% 
  filter(user_opinion_function == "Konsens") %>% 
  filter(relevance_gravity == 0) %>% 
  mutate(steps = factor(steps)) %>% 
  ggplot() +
  aes(x = area_under_gini, y = area_under_ndcg, color = steps, shape= user_opinion_function, group= seed) + # , color = vote_count, shape = user_opinion_function, fill = init_score) + 
  theme(text=element_text(family="Trebuchet MS")) +
  geom_point(alpha = 0.4) + 
  #geom_line(alpha = 0.4) +
  facet_wrap(~scoring_function)
```
```{r}
df_steps %>% 
  filter(user_opinion_function == "Konsens") %>% 
  mutate(steps = factor(steps)) %>% 
  ggplot_cus() + 
  theme(legend.position = "left") + 
  aes(x = area_under_gini, y = area_under_ndcg, size = posts_with_no_views, color = steps) + 
  geom_point(alpha = 0.5) + 
  facet_grid(relevance_gravity~scoring_function) 
  
if(s)
{
  ggsave("/home/ludwig/Bachelorarbeit/voting-protocols/plots/steps_scatter.png", device = "png")
}
```

```{r}
df_steps %>% 
  mutate(steps = factor(steps)) %>% 
  filter(user_opinion_function == "Konsens") %>% 
  filter(relevance_gravity == 0) %>% 
  ggplot_cus() +
  aes(fill = scoring_function,y =  area_under_gini, x = steps) + 
  theme(legend.position = "none") + 
  geom_boxplot()  + 
  facet_wrap(~relevance_gravity)

if(s)
{
  ggsave("/home/ludwig/Bachelorarbeit/voting-protocols/plots/steps_gini.png", device = "png")
}
```

```{r}
df_steps %>% 
 # filter(steps <= 100) %>% 
  filter(user_opinion_function == "Konsens") %>% 
  filter(relevance_gravity == 0) %>% 
  mutate(quality_dimensions = factor(quality_dimensions)) %>% 
  mutate(steps = factor(steps)) %>% 
  ggplot_cus() +
  theme(legend.position = "none") + 
  aes(fill = scoring_function,y =  area_under_ndcg, x = steps) + 
  geom_boxplot() + 
  facet_wrap(~relevance_gravity)

if(s)
{
  ggsave("/home/ludwig/Bachelorarbeit/voting-protocols/plots/steps_ndcg.png", device = "png")
}
```


```{r}
df_steps %>% 
 # filter(steps <= 100) %>% 
  filter(user_opinion_function == "Konsens") %>% 
  filter(relevance_gravity == 0) %>% 
  mutate(quality_dimensions = factor(quality_dimensions)) %>% 
  mutate(steps = factor(steps)) %>% 
  ggplot_cus() +
    theme(legend.position = "none") + 

  aes(fill = scoring_function,y =  posts_with_no_views, x = steps) + 
  geom_boxplot() + 
  facet_wrap(~relevance_gravity)

if(s)
{
  ggsave("/home/ludwig/Bachelorarbeit/voting-protocols/plots/steps_pwnv.png", device = "png")
}

```


```{r}
df_steps %>% 
 # filter(steps <= 100) %>% 
  filter(user_opinion_function == "Konsens") %>% 
  filter(relevance_gravity == 0) %>% 
  mutate(quality_dimensions = factor(quality_dimensions)) %>% 
  mutate(steps = factor(steps)) %>% 
  ggplot() +
    theme(legend.position = "none") + 

  aes(fill = scoring_function,y =  ρ) + 
  theme(text=element_text(family="Trebuchet MS")) +
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank(),) +
  geom_boxplot() + 
  facet_wrap(~steps,ncol = nrow(unique(df_steps[,"steps"])))

```
```{r}
to_spear = df_steps %>% 
  filter(user_opinion_function == "Konsens") %>% 
  filter(relevance_gravity == 0)
  #filter(scoring_function == "Veralg. Hacker News")

spear_100 = to_spear%>% 
  filter(steps == 100)

spear_300 = to_spear %>% 
  filter(steps == 300)

spear_500 = to_spear %>% 
  filter(steps == 500)

spear_1000 = to_spear %>% 
  filter(steps == 1000)


spear_tib = tibble(s100 = spear_100$ρ, s300 = spear_300$ρ, s500 = spear_500$ρ, s1000 = spear_1000$ρ)


ggcorrplot(cor(spear_tib, method = "spearman"),ggtheme = theme(text=element_text(family="Trebuchet MS")), lab = FALSE, colors = c("#6D9EC1", "white", "#E46726"), legend.title = "Spearman von ρ")

```
```{r}
ggcorrplot(corr_matrix(df_steps, "steps"),ggtheme = theme(text=element_text(family="Trebuchet MS")), lab = FALSE, colors = c("#6D9EC1", "white", "#E46726"), legend.title = "Spearman von ρ")
```


```{r}
df_steps %>% 
 # filter(steps <= 100) %>% 
  mutate(steps = factor(steps)) %>% 
  ggplot() +
  aes(color = scoring_function,x=area_under_gini,y =  area_under_ndcg, group = seed, shape = user_opinion_function) + 
  theme(text=element_text(family="Trebuchet MS")) +
  #theme(axis.text.x=element_blank(),axis.ticks.x=element_blank(),) +
  geom_point(alpha = 0.5) + 
  geom_line(alpha = 0.3) +
  facet_wrap(~quality_dimensions)
  #facet_wrap(~steps,ncol = nrow(unique(tmp_df[,"steps"])))

```
